services:
  - type: worker
    name: monitor-sitios
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    schedule: "*/10 * * * *"  # Ejecutar cada 10 minutos
